services:

  main:
    image: mohamednabil404/express-test
    ports:
      - 8080:8080
    container_name: express-test
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower